// Function: entry

/* WARNING: Instruction at (ram,0x0001023f) overlaps instruction at (ram,0x0001023d)
    */
/* WARNING: Stack frame is not setup normally: Input value of stackpointer is not used */
/* WARNING: This function may have set the stack pointer */
/* WARNING: Removing unreachable block (ram,0x00010014) */
/* WARNING: Removing unreachable block (ram,0x00010043) */
/* WARNING: Removing unreachable block (ram,0x00010023) */
/* WARNING: Removing unreachable block (ram,0x0001002b) */
/* WARNING: Removing unreachable block (ram,0x00010059) */
/* WARNING: Removing unreachable block (ram,0x0001006f) */

void entry(void)

{
  char *pcVar1;
  byte *pbVar2;
  int *piVar3;
  undefined2 *puVar4;
  code *pcVar5;
  char *pcVar6;
  char cVar7;
  byte bVar8;
  undefined1 uVar9;
  int iVar10;
  char in_CL;
  undefined2 extraout_DX;
  byte bVar12;
  undefined2 extraout_DX_00;
  undefined2 uVar11;
  int in_BX;
  int iVar13;
  undefined1 *puVar14;
  int *piVar15;
  int *piVar16;
  int unaff_BP;
  undefined2 *puVar17;
  int iVar18;
  undefined2 *in_ESI;
  undefined2 *puVar19;
  undefined2 *unaff_DI;
  int iVar20;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  undefined2 uVar21;
  bool bVar22;
  
  puVar14 = (undefined1 *)0xfffe;
  DAT_1000_fffe = 3;
  cVar7 = FUN_1000_002e();
  *(undefined1 **)(puVar14 + -2) = puVar14;
  piVar15 = (int *)(puVar14 + -4);
  *(undefined2 *)(puVar14 + -4) = 0x7369;
  puVar17 = (undefined2 *)in_ESI;
  pbVar2 = (byte *)((int)puVar17 + in_BX + 0x72);
  bVar12 = (byte)((uint)extraout_DX >> 8);
  *pbVar2 = *pbVar2 & bVar12;
  puVar4 = puVar17 + 1;
  puVar19 = (undefined2 *)CONCAT22((int)((ulong)in_ESI >> 0x10),puVar4);
  out(*puVar17,extraout_DX);
  uVar11 = in(extraout_DX);
  *unaff_DI = uVar11;
  pbVar2 = (byte *)((int)puVar4 + unaff_BP + 0x65);
  *pbVar2 = *pbVar2 & bVar12;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(in_BX + (int)puVar4) = *(char *)(in_BX + (int)puVar4) + cVar7;
  *(char *)(unaff_BP + 0x45) = *(char *)(unaff_BP + 0x45) + in_CL;
  pcVar5 = (code *)swi(1);
  bVar8 = (*pcVar5)();
  iVar10 = *piVar15;
  pcVar6 = (char *)((int)(undefined2 *)puVar19 + 1);
  out(*(undefined1 *)puVar19,extraout_DX_00);
  bVar8 = bVar8 | (byte)unaff_DI[1];
  *pcVar6 = *pcVar6;
  *pcVar6 = *pcVar6 + (char)extraout_DX_00;
  pcVar6[iVar10] = pcVar6[iVar10] + bVar8;
  pcVar6[iVar10] = pcVar6[iVar10] + bVar8;
  pcVar6[iVar10] = pcVar6[iVar10] + bVar8;
  pbVar2 = (byte *)(pcVar6 + iVar10);
  bVar12 = *pbVar2;
  *pbVar2 = *pbVar2 + bVar8;
  pcVar6[iVar10] = pcVar6[iVar10] | bVar8 - CARRY1(bVar12,bVar8);
  iVar20 = piVar15[1];
  iVar18 = piVar15[2];
  iVar13 = piVar15[5];
  uVar11 = piVar15[6];
  iVar10 = piVar15[8];
  piVar16 = piVar15 + 8;
  piVar15[8] = 0x1000;
  iVar10 = iVar10 + 1;
  *(char *)(iVar13 + iVar18) = *(char *)(iVar13 + iVar18) + (char)((uint)iVar10 >> 8);
  piVar3 = (int *)(iVar13 + iVar18 + -0x77ff);
  *piVar3 = *piVar3 + iVar10;
  piVar3 = (int *)(iVar13 + iVar18 + -0x10ff);
  *piVar3 = *piVar3 + iVar13;
  *(char *)(iVar13 + iVar18) = *(char *)(iVar13 + iVar18) + (char)iVar10;
  cVar7 = (char)iVar10 + (char)((uint)uVar11 >> 8);
  *(undefined2 *)(iVar18 + 0x401) = *(undefined2 *)(iVar18 + 0x401);
  pcVar1 = (char *)(iVar18 + 0x401);
  bVar22 = SCARRY1(*pcVar1,cVar7);
  *pcVar1 = *pcVar1 + cVar7;
  uVar21 = (undefined2)((ulong)*(undefined4 *)(iVar13 + iVar20) >> 0x10);
  uVar9 = in(uVar11);
  while( true ) {
    *(undefined1 *)(iVar13 + iVar18 + 2) = uVar9;
    uVar9 = in(uVar11);
    *(undefined1 *)(iVar20 + -0x46f6) = (char)uVar11;
    if (!bVar22) break;
    bVar22 = SCARRY2((int)((int)piVar16 + 2),0x400);
    piVar16 = (int *)((int)piVar16 + 0x402);
  }
  pcVar5 = (code *)swi(1);
  (*pcVar5)();
  return;
}

