// Function: FUN_1000_002e

/* WARNING: Instruction at (ram,0x0001023f) overlaps instruction at (ram,0x0001023d)
    */

void FUN_1000_002e(void)

{
  char *pcVar1;
  byte *pbVar2;
  int *piVar3;
  byte bVar4;
  code *pcVar5;
  char *pcVar6;
  char cVar7;
  byte bVar8;
  undefined1 uVar9;
  undefined2 extraout_DX;
  int in_BX;
  int iVar10;
  undefined4 in_ESI;
  undefined1 *puVar11;
  undefined2 *unaff_DI;
  undefined2 unaff_SS;
  undefined2 uVar12;
  bool bVar13;
  int in_stack_0000000e;
  int in_stack_00000010;
  int in_stack_00000012;
  int in_stack_00000018;
  undefined2 in_stack_0000001a;
  int in_stack_0000001e;
  
  pcVar5 = (code *)swi(0x21);
  (*pcVar5)();
  pcVar5 = (code *)swi(0x21);
  cVar7 = (*pcVar5)();
  iVar10 = (int)in_ESI;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  *(char *)(in_BX + iVar10) = *(char *)(in_BX + iVar10) + cVar7;
  puVar11 = (undefined1 *)CONCAT22((int)((ulong)in_ESI >> 0x10),(undefined1 *)(iVar10 + -1));
  pcVar5 = (code *)swi(1);
  bVar8 = (*pcVar5)();
  pcVar6 = (undefined1 *)puVar11 + 1;
  out(*puVar11,extraout_DX);
  bVar8 = bVar8 | (byte)*unaff_DI;
  *pcVar6 = *pcVar6;
  *pcVar6 = *pcVar6 + (char)extraout_DX;
  pcVar6[in_stack_0000000e] = pcVar6[in_stack_0000000e] + bVar8;
  pcVar6[in_stack_0000000e] = pcVar6[in_stack_0000000e] + bVar8;
  pcVar6[in_stack_0000000e] = pcVar6[in_stack_0000000e] + bVar8;
  pbVar2 = (byte *)(pcVar6 + in_stack_0000000e);
  bVar4 = *pbVar2;
  *pbVar2 = *pbVar2 + bVar8;
  pcVar6[in_stack_0000000e] = pcVar6[in_stack_0000000e] | bVar8 - CARRY1(bVar4,bVar8);
  in_stack_0000001e = in_stack_0000001e + 1;
  *(char *)(in_stack_00000018 + in_stack_00000012) =
       *(char *)(in_stack_00000018 + in_stack_00000012) + (char)((uint)in_stack_0000001e >> 8);
  piVar3 = (int *)(in_stack_00000018 + in_stack_00000012 + -0x77ff);
  *piVar3 = *piVar3 + in_stack_0000001e;
  piVar3 = (int *)(in_stack_00000018 + in_stack_00000012 + -0x10ff);
  *piVar3 = *piVar3 + in_stack_00000018;
  *(char *)(in_stack_00000018 + in_stack_00000012) =
       *(char *)(in_stack_00000018 + in_stack_00000012) + (char)in_stack_0000001e;
  cVar7 = (char)in_stack_0000001e + (char)((uint)in_stack_0000001a >> 8);
  *(undefined2 *)(in_stack_00000012 + 0x401) = *(undefined2 *)(in_stack_00000012 + 0x401);
  pcVar1 = (char *)(in_stack_00000012 + 0x401);
  bVar13 = SCARRY1(*pcVar1,cVar7);
  *pcVar1 = *pcVar1 + cVar7;
  uVar12 = (undefined2)((ulong)*(undefined4 *)(in_stack_00000018 + in_stack_00000010) >> 0x10);
  uVar9 = in(in_stack_0000001a);
  while( true ) {
    *(undefined1 *)(in_stack_00000018 + in_stack_00000012 + 2) = uVar9;
    uVar9 = in(in_stack_0000001a);
    *(undefined1 *)(in_stack_00000010 + -0x46f6) = (char)in_stack_0000001a;
    if (!bVar13) break;
    bVar13 = SCARRY2((int)&stack0x0020,0x400);
  }
  pcVar5 = (code *)swi(1);
  (*pcVar5)();
  return;
}

