// Function: entry

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Stack frame is not setup normally: Input value of stackpointer is not used */
/* WARNING: This function may have set the stack pointer */
/* WARNING: Removing unreachable block (ram,0x00010014) */
/* WARNING: Removing unreachable block (ram,0x00010023) */
/* WARNING: Removing unreachable block (ram,0x0001002b) */
/* WARNING: Removing unreachable block (ram,0x0001002d) */
/* WARNING: Removing unreachable block (ram,0x00010038) */
/* WARNING: Removing unreachable block (ram,0x00010043) */
/* WARNING: Removing unreachable block (ram,0x0001006f) */

void entry(void)

{
  uint *puVar1;
  byte *pbVar2;
  int *piVar3;
  undefined2 *puVar4;
  byte *pbVar5;
  undefined2 uVar6;
  code *pcVar7;
  char cVar8;
  uint uVar9;
  int iVar10;
  char in_CL;
  char in_CH;
  byte bVar11;
  char *in_BX;
  undefined1 *puVar12;
  int unaff_BP;
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  longdouble in_ST0;
  undefined4 uVar13;
  
  puVar12 = (undefined1 *)0xfffe;
  uRam0001fffe = 3;
  uVar13 = FUN_1000_0038();
  iVar10 = (int)((ulong)uVar13 >> 0x10);
  *(undefined1 **)(puVar12 + -2) = puVar12;
  *(undefined2 *)(puVar12 + -4) = 0x7369;
  bVar11 = (byte)((ulong)uVar13 >> 0x18);
  (in_BX + (int)unaff_SI)[0x72] = (in_BX + (int)unaff_SI)[0x72] & bVar11;
  puVar4 = unaff_SI + 1;
  out(*unaff_SI,iVar10);
  cVar8 = (char)uVar13;
  pbVar5 = (byte *)(unaff_DI + 1);
  uVar6 = in(iVar10);
  *unaff_DI = uVar6;
  pbVar2 = (byte *)((int)puVar4 + unaff_BP + 0x65);
  *pbVar2 = *pbVar2 & bVar11;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  *(char *)(unaff_BP + 0x45) = *(char *)(unaff_BP + 0x45) + in_CL;
  *(uint *)0x6a01 = (uint)uVar13;
  puVar1 = (uint *)(unaff_BP + (int)puVar4);
  uVar9 = *puVar1;
  *puVar1 = *puVar1 + (int)puVar4;
  if (!CARRY2(uVar9,(uint)puVar4)) {
    cVar8 = cVar8 + '\x11';
    *(char *)0x415 = *(char *)0x415 + bVar11;
    pbVar5[unaff_BP] = pbVar5[unaff_BP] + cVar8;
    in_BX[(int)pbVar5] = in_BX[(int)pbVar5];
    in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
    in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
    *(undefined2 *)(puVar12 + -6) = 0x1000;
    *(undefined2 *)(puVar12 + -8) = 0x287;
    iVar10 = func_0x00034109();
    LOCK();
    *(int *)(in_BX + (int)puVar4) = *(int *)(in_BX + (int)puVar4) + iVar10;
    UNLOCK();
    in_BX[(int)puVar4] = in_BX[(int)puVar4] + (char)iVar10;
    cVar8 = (char)iVar10 + -0x80;
    *(int *)(in_BX + (int)puVar4) =
         *(int *)(in_BX + (int)puVar4) + CONCAT11((char)((uint)iVar10 >> 8),cVar8);
    in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
    in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
    *(long *)(in_BX + (int)pbVar5) = (long)in_ST0;
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  uVar9 = (uint)uVar13 | *(uint *)0x700;
  cVar8 = (char)uVar9;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  *(char *)((int)unaff_SI + 0x103) = *(char *)((int)unaff_SI + 0x103) + in_CH;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  *in_BX = *in_BX + cVar8;
  *in_BX = *in_BX + cVar8;
  pbVar5[unaff_BP] = pbVar5[unaff_BP] + cVar8;
  *(char *)(unaff_BP + 0x4000) = *(char *)(unaff_BP + 0x4000) + in_CH;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + (char)((uint)in_BX >> 8);
  in_BX[(int)pbVar5] = in_BX[(int)pbVar5] + -0x74;
  piVar3 = (int *)((int)puVar4 + unaff_BP + 0xd01);
  *piVar3 = *piVar3 + iVar10;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  cVar8 = cVar8 + in_BX[(int)puVar4];
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  in_BX[(int)puVar4] = in_BX[(int)puVar4] + cVar8;
  out(iVar10,CONCAT11((char)(uVar9 >> 8),cVar8));
  *(undefined1 **)(in_BX + (int)puVar4) = puVar12 + *(int *)(in_BX + (int)puVar4) + -2;
  *pbVar5 = *pbVar5 & cVar8 + 0x50U;
  unaff_SI[0x39] = -unaff_SI[0x39];
  pcVar7 = (code *)swi(1);
  (*pcVar7)();
  return;
}

